### ISSUE TITLE
无法编译

### ISSUE THREAD

**Issue by Alanqiu** [OpenIMSDK/Open-IM-Android-Demo#10]
![image](https://user-images.githubusercontent.com/5857925/189093829-6c4fbb08-9881-44a5-a878-f2fde646ef3d.png)
这个文件夹是空的，为什么还要引入

**Comment by JINMUSENG** [comment]
拉新版试下

**Comment by Alanqiu** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
