### ISSUE TITLE
The 'api 'com.github.lihangleo2:ShadowLayout:2.0.1'' cannot be found. [Resolved]

### ISSUE THREAD

**Issue by NSnidie** [openimsdk/open-im-android-demo#13]
官方[JitPack](https://jitpack.io/)
可以看到"2.0.1"已经不再支持，换成最新的3.3.3就行

**Comment by dylanZk1** [comment]
我是直接把源码给扒下来后引入的，也方便自定义

**Comment by jiaweizeng** [comment]
Open-IM-Android-Demo-main\OUIKit\OUIConversation\build\generated\data_binding_base_class_source_out\release\out\io\openim\android\ouiconversation\databinding\ActivityChatBinding.java:18: 错误: 程序包com.lihang不存在
import com.lihang.ShadowLayout;

改为3.3.3版本后运行怎么提示找不到这个包
