### ISSUE TITLE
Could not GET 'https://open-im-online.rentsoft.cn:51000/repository/maven2/com/huawei/agconnect/agcp/1.6.0.300/agcp-1.6.0.300.pom'. Received status code 502 from server: Bad Gateway 

### ISSUE THREAD

**Issue by jiaweizeng** [openimsdk/open-im-android-demo#18]
### What would you like to share?

Could not GET 'https://open-im-online.rentsoft.cn:51000/repository/maven2/com/huawei/agconnect/agcp/1.6.0.300/agcp-1.6.0.300.pom'. Received status code 502 from server: Bad Gateway

把华为的推送相关的注释掉，会影响IM的功能吗？

**Comment by Oliver-WJ** [comment]
不会
