### ISSUE TITLE
couldn't run the demo code

### ISSUE THREAD

**Issue by tmsbyim01** [openimsdk/open-im-android-demo#34]
### What happened?

clone this code, when building in cell phone, then get some errors

org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':OUICore:debugCompileClasspath'.
org.gradle.internal.resolve.ArtifactResolveException: Could not download android-sdk-3.5.1.aar (io.openim:android-sdk:3.5.1)
org.gradle.api.resources.ResourceException: Could not get resource 'https://open-im-online.rentsoft.cn:51000/repository/maven2/io/openim/android-sdk/3.5.1/android-sdk-3.5.1.aar'.
org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 111,093; received: 32,277)
org.gradle.internal.resolve.ArtifactResolveException: Could not download core-sdk-3.5.1.aar (io.openim:core-sdk:3.5.1)
org.gradle.api.resources.ResourceException: Could not get resource 'https://open-im-online.rentsoft.cn:51000/repository/maven2/io/openim/core-sdk/3.5.1/core-sdk-3.5.1.aar'.
org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 27,488,871; received: 32,275)
org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':OUICore:debugCompileClasspath'.
org.gradle.internal.resolve.ArtifactResolveException: Could not download android-sdk-3.5.1.aar (io.openim:android-sdk:3.5.1)
org.gradle.api.resources.ResourceException: Could not get resource 'https://open-im-online.rentsoft.cn:51000/repository/maven2/io/openim/android-sdk/3.5.1/android-sdk-3.5.1.aar'.
org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 111,093; received: 32,277)
org.gradle.internal.resolve.ArtifactResolveException: Could not download core-sdk-3.5.1.aar (io.openim:core-sdk:3.5.1)
org.gradle.api.resources.ResourceException: Could not get resource 'https://open-im-online.rentsoft.cn:51000/repository/maven2/io/openim/core-sdk/3.5.1/core-sdk-3.5.1.aar'.
org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 27,488,871; received: 32,275)
org.gradle.api.internal.tasks.properties.PropertyEvaluationException: Error while evaluating property 'annotationProcessorClassNames' of task ':OUIContact:javaPreCompileDebug'
org.gradle.api.internal.provider.AbstractProperty$PropertyQueryException: Failed to calculate the value of task ':OUIContact:javaPreCompileDebug' property 'annotationProcessorClassNames'.
org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':OUIContact:debugRuntimeClasspath'.
org.gradle.api.internal.artifacts.transform.TransformException: Failed to transform android-sdk-3.5.1.aar (io.openim:android-sdk:3.5.1) to match attributes {artifactType=android-symbol-with-package-name, org.gradle.status=release}.
org.gradle.internal.resolve.ArtifactResolveException: Could not download android-sdk-3.5.1.aar (io.openim:android-sdk:3.5.1)
org.gradle.api.resources.ResourceException: Could not get resource 'https://open-im-online.rentsoft.cn:51000/repository/maven2/io/openim/android-sdk/3.5.1/android-sdk-3.5.1.aar'.
org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 111,093; received: 32,277)
org.gradle.api.internal.tasks.properties.PropertyEvaluationException: Error while evaluating property 'annotationProcessorClassNames' of task ':OUICore:javaPreCompileDebug'
org.gradle.api.internal.provider.AbstractProperty$PropertyQueryException: Failed to calculate the value of task ':OUICore:javaPreCompileDebug' property 'annotationProcessorClassNames'.
org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':OUICore:debugRuntimeClasspath'.
org.gradle.api.internal.artifacts.transform.TransformException: Failed to transform android-sdk-3.5.1.aar (io.openim:android-sdk:3.5.1) to match attributes {artifactType=android-symbol-with-package-name, org.gradle.status=release}.
org.gradle.internal.resolve.ArtifactResolveException: Could not download android-sdk-3.5.1.aar (io.openim:android-sdk:3.5.1)
org.gradle.api.resources.ResourceException: Could not get resource 'https://open-im-online.rentsoft.cn:51000/repository/maven2/io/openim/android-sdk/3.5.1/android-sdk-3.5.1.aar'.
org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 111,093; received: 32,277)
org.gradle.api.internal.tasks.properties.PropertyEvaluationException: Error while evaluating property 'annotationProcessorClassNames' of task ':OUIConversation:javaPreCompileDebug'
org.gradle.api.internal.provider.AbstractProperty$PropertyQueryException: Failed to calculate the value of task ':OUIConversation:javaPreCompileDebug' property 'annotationProcessorClassNames'.
org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':OUIConversation:debugRuntimeClasspath'.
org.gradle.api.internal.artifacts.transform.TransformException: Failed to transform android-sdk-3.5.1.aar (io.openim:android-sdk:3.5.1) to match attributes {artifactType=android-symbol-with-package-name, org.gradle.status=release}.
org.gradle.internal.resolve.ArtifactResolveException: Could not download android-sdk-3.5.1.aar (io.openim:android-sdk:3.5.1)
org.gradle.api.resources.ResourceException: Could not get resource 'https://open-im-online.rentsoft.cn:51000/repository/maven2/io/openim/android-sdk/3.5.1/android-sdk-3.5.1.aar'.
org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 111,093; received: 32,277)
org.gradle.api.internal.tasks.properties.PropertyEvaluationException: Error while evaluating property 'annotationProcessorClassNames' of task ':OUIGroup:javaPreCompileDebug'
org.gradle.api.internal.provider.AbstractProperty$PropertyQueryException: Failed to calculate the value of task ':OUIGroup:javaPreCompileDebug' property 'annotationProcessorClassNames'.
org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':OUIGroup:debugRuntimeClasspath'.
org.gradle.api.internal.artifacts.transform.TransformException: Failed to transform android-sdk-3.5.1.aar (io.openim:android-sdk:3.5.1) to match attributes {artifactType=android-symbol-with-package-name, org.gradle.status=release}.
org.gradle.internal.resolve.ArtifactResolveException: Could not download android-sdk-3.5.1.aar (io.openim:android-sdk:3.5.1)
org.gradle.api.resources.ResourceException: Could not get resource 'https://open-im-online.rentsoft.cn:51000/repository/maven2/io/openim/android-sdk/3.5.1/android-sdk-3.5.1.aar'.
org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 111,093; received: 32,277)
org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
org.gradle.internal.resolve.ArtifactResolveException: Could not download android-sdk-3.5.1.aar (io.openim:android-sdk:3.5.1)
org.gradle.api.resources.ResourceException: Could not get resource 'https://open-im-online.rentsoft.cn:51000/repository/maven2/io/openim/android-sdk/3.5.1/android-sdk-3.5.1.aar'.
org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 111,093; received: 32,277)
org.gradle.internal.resolve.ArtifactResolveException: Could not download core-sdk-3.5.1.aar (io.openim:core-sdk:3.5.1)
org.gradle.api.resources.ResourceException: Could not get resource 'https://open-im-online.rentsoft.cn:51000/repository/maven2/io/openim/core-sdk/3.5.1/core-sdk-3.5.1.aar'.
org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 27,488,871; received: 32,275)
org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
org.gradle.internal.resolve.ArtifactResolveException: Could not download android-sdk-3.5.1.aar (io.openim:android-sdk:3.5.1)
org.gradle.api.resources.ResourceException: Could not get resource 'https://open-im-online.rentsoft.cn:51000/repository/maven2/io/openim/android-sdk/3.5.1/android-sdk-3.5.1.aar'.
org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 111,093; received: 32,277)
org.gradle.internal.resolve.ArtifactResolveException: Could not download core-sdk-3.5.1.aar (io.openim:core-sdk:3.5.1)
org.gradle.api.resources.ResourceException: Could not get resource 'https://open-im-online.rentsoft.cn:51000/repository/maven2/io/openim/core-sdk/3.5.1/core-sdk-3.5.1.aar'.
org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 27,488,871; received: 32,275)
org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
org.gradle.internal.resolve.ArtifactResolveException: Could not download android-sdk-3.5.1.aar (io.openim:android-sdk:3.5.1)
org.gradle.api.resources.ResourceException: Could not get resource 'https://open-im-online.rentsoft.cn:51000/repository/maven2/io/openim/android-sdk/3.5.1/android-sdk-3.5.1.aar'.
org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 111,093; received: 32,277)
org.gradle.internal.resolve.ArtifactResolveException: Could not download core-sdk-3.5.1.aar (io.openim:core-sdk:3.5.1)
org.gradle.api.resources.ResourceException: Could not get resource 'https://open-im-online.rentsoft.cn:51000/repository/maven2/io/openim/core-sdk/3.5.1/core-sdk-3.5.1.aar'.
org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 27,488,871; received: 32,275)
org.gradle.api.internal.tasks.properties.PropertyEvaluationException: Error while evaluating property 'annotationProcessorClassNames' of task ':app:javaPreCompileDebug'
org.gradle.api.internal.provider.AbstractProperty$PropertyQueryException: Failed to calculate the value of task ':app:javaPreCompileDebug' property 'annotationProcessorClassNames'.
org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
org.gradle.api.internal.artifacts.transform.TransformException: Failed to transform android-sdk-3.5.1.aar (io.openim:android-sdk:3.5.1) to match attributes {artifactType=android-symbol-with-package-name, org.gradle.status=release}.
org.gradle.internal.resolve.ArtifactResolveException: Could not download android-sdk-3.5.1.aar (io.openim:android-sdk:3.5.1)
org.gradle.api.resources.ResourceException: Could not get resource 'https://open-im-online.rentsoft.cn:51000/repository/maven2/io/openim/android-sdk/3.5.1/android-sdk-3.5.1.aar'.
org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 111,093; received: 32,277)
org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
org.gradle.internal.resolve.ArtifactResolveException: Could not download android-sdk-3.5.1.aar (io.openim:android-sdk:3.5.1)
org.gradle.api.resources.ResourceException: Could not get resource 'https://open-im-online.rentsoft.cn:51000/repository/maven2/io/openim/android-sdk/3.5.1/android-sdk-3.5.1.aar'.
org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 111,093; received: 32,277)
org.gradle.internal.resolve.ArtifactResolveException: Could not download core-sdk-3.5.1.aar (io.openim:core-sdk:3.5.1)
org.gradle.api.resources.ResourceException: Could not get resource 'https://open-im-online.rentsoft.cn:51000/repository/maven2/io/openim/core-sdk/3.5.1/core-sdk-3.5.1.aar'.
org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 27,488,871; received: 32,275)
org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
org.gradle.internal.resolve.ArtifactResolveException: Could not download android-sdk-3.5.1.aar (io.openim:android-sdk:3.5.1)
org.gradle.api.resources.ResourceException: Could not get resource 'https://open-im-online.rentsoft.cn:51000/repository/maven2/io/openim/android-sdk/3.5.1/android-sdk-3.5.1.aar'.
org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 111,093; received: 32,277)
org.gradle.internal.resolve.ArtifactResolveException: Could not download core-sdk-3.5.1.aar (io.openim:core-sdk:3.5.1)
org.gradle.api.resources.ResourceException: Could not get resource 'https://open-im-online.rentsoft.cn:51000/repository/maven2/io/openim/core-sdk/3.5.1/core-sdk-3.5.1.aar'.
org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 27,488,871; received: 32,275)
org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
org.gradle.internal.resolve.ArtifactResolveException: Could not download android-sdk-3.5.1.aar (io.openim:android-sdk:3.5.1)
org.gradle.api.resources.ResourceException: Could not get resource 'https://open-im-online.rentsoft.cn:51000/repository/maven2/io/openim/android-sdk/3.5.1/android-sdk-3.5.1.aar'.
org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 111,093; received: 32,277)
org.gradle.internal.resolve.ArtifactResolveException: Could not download core-sdk-3.5.1.aar (io.openim:core-sdk:3.5.1)
org.gradle.api.resources.ResourceException: Could not get resource 'https://open-im-online.rentsoft.cn:51000/repository/maven2/io/openim/core-sdk/3.5.1/core-sdk-3.5.1.aar'.
org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 27,488,871; received: 32,275)

### What did you expect to happen?

successful running

### How can we reproduce it (as minimally and precisely as possible)?

clone it and running again

### Anything else we need to know?

可以用中文

### version

<details>
```console
$ {name} version
# paste output here
```
</details>

### Cloud provider

<details>
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by OCTestX** [comment]
我不知道你们是怎样的，我打开项目无法识别gradle，直到我打开项目文件夹的Demo文件夹，一切正常运行

**Comment by OCTestX** [comment]
![Screenshot_20240804_153322](https://github.com/user-attachments/assets/7f4f8d40-a0e9-49fc-9919-69342af77304)

**Comment by OCTestX** [comment]
也许你应该尝试使用代理

**Comment by chenyu1990** [comment]
这个open-im的文档是真的烂
flutter
react-native
还有这个，全试了，没一个可以跑起来的！无语死了

**Comment by JauneQ** [comment]
Try to clean your gradle's cache folder, and rebuild it.

**Comment by buiphukhuyen** [comment]
Same error
