### ISSUE TITLE
[BUG] Demo http://43.128.72.19:10008/  服务器超时  

### ISSUE THREAD

**Issue by wukuiqing49** [openimsdk/open-im-android-demo#37]
### OpenIM Server Version

最新版本Demo

### Operating System and CPU Architecture

Windows (ARM)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

服务器地址有新的吗 想运行下Demo (Android)

### Screenshots Link

![1726307102318](https://github.com/user-attachments/assets/f346d143-0182-4577-a0ba-347a30873cdd)

**Comment by wukuiqing49** [comment]
close

**Comment by skiffer-git** [comment]
You need to deploy OpenIMServer on your own machine.
