### ISSUE TITLE
[BUG] The "withdraw message" reminder keeps appearing at the top of the group's messages. 

### ISSUE THREAD

**Issue by shunai** [openimsdk/open-im-android-demo#44]
### OpenIM Server Version

3.8.1

### Operating System and CPU Architecture

Linux (ARM)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

1. 通过SDK 发了一条消息，时间为2026年11月01日
2. 撤回此消息，“撤回消息”提醒一直保持群组的消息最前列

### Screenshots Link

![image](https://github.com/user-attachments/assets/31fafd55-3c2d-48c5-aa6c-4b0dd79708d6)
![image](https://github.com/user-attachments/assets/bb4eec37-c8bb-4905-9412-84241d54b8b8)

**Comment by JauneQ** [comment]
Try to update your demo app, we fixed this problem.
