### ISSUE TITLE
[FEATURE REQUEST] I’d like to have setup guides for enabling notification alerts on various smartphone brands.

### ISSUE THREAD

**Issue by shunai** [openimsdk/open-im-android-demo#45]
### Why this feature?

不同用户的手机品牌不一样，其消息设置也不一样

### Suggested Solution

希望有个统一的官方文档指引设置

**Comment by JauneQ** [comment]
Did you means offline push notification services? The demo just used to display how to use our sdk, if you want to use service like FCM, you perhaps need to read their docs.
