### ISSUE TITLE
[DOC]: The setConversion method exists in the documentation, but it does not exist when used 3.8.1

### ISSUE THREAD

**Issue by Hefnegshe** [openimsdk/open-im-android-demo#47]
![Uploading 9dcd9ed4dfe0bfb698c70cbaa6c5b6d.png…]()
## Documentation Updates
Describe the documentation that needs to be updated or corrected. Please specify the files and sections if possible.

## Motivation
Explain why these updates are necessary. What is missing, misleading, or outdated?

## Suggested Changes
Detail the changes that you propose. If you are suggesting large changes, include examples or mockups of what the updated documentation should look like.

## Additional Information
Include any other information that might be relevant, such as links to discussions or related issues in the repository.

**Comment by JauneQ** [comment]
Please make sure your local code is up to date. If using remote dependencies, please make sure you are using the correct versions.
