### ISSUE TITLE
[BUG] Voice call interruption

### ISSUE THREAD

**Issue by Eternaldreamss** [openimsdk/open-im-android-demo#48]
### OpenIM Server Version

io.openim:android-sdk:3.5.1-beta1@aar

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

During a voice call, one party suddenly cannot hear the sound, and after a while, the other party also cannot hear the sound. At this time, there is no obvious error in the APP, and the interface shows that the call is still in progress.

**Comment by JauneQ** [comment]
Try update your sdk to 3.8.1. If the problem still exists, you can create issue in [here](https://github.com/openimsdk/open-im-sdk-android/issues).
