### ISSUE TITLE
android

### ISSUE THREAD

**Issue by wangjincheng123-ai** [openimsdk/open-im-android-demo#49]
### OpenIM Server Version

3.8.0

### Operating System and CPU Architecture

Windows (ARM)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

您好,请问下,android demo启动
demo文件夹下config.gradle文件中,isModule的值为false还是为ture
app文件夹下的 implementation project(':OUICalling')  这行代码需要注释吗??
在哪个文件中修改本地连接配置

**Comment by JauneQ** [comment]
Please read [it](https://github.com/openimsdk/open-im-android-demo/blob/main/README.md) first, if you are unsure, compile with the default configuration.
