### ISSUE TITLE
[BUG] Android demo compile error

### ISSUE THREAD

**Issue by Jerricc** [openimsdk/open-im-android-demo#56]
### OpenIM Server Version

3.8.0

### Operating System and CPU Architecture

macOS (ARM)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

<img width="2145" alt="image" src="https://github.com/user-attachments/assets/015cdd1e-e6bb-4e0d-be83-7a16e6307eba" />
Android demo compile error

**Comment by JauneQ** [comment]
Check your network and re-execute gradle sync after confirming it is available.
