### ISSUE TITLE
Minimum supported Gradle version is 7.3.3. Current version is 7.2.

### ISSUE THREAD

**Issue by harryheng** [OpenIMSDK/Open-IM-Android-Demo#6]
Minimum supported Gradle version is 7.3.3. Current version is 7.2.

Please fix the project's Gradle settings.
Change Gradle version in Gradle wrapper to 7.3.3 and re-import project
Open Gradle wrapper properties
Gradle Settings.

**Comment by JINMUSENG** [comment]
Gradle Settings depends on your development environment. I can run gradle-5.4.1
